export const INIT_PAIR_ARRAY = 'INIT_PAIR_ARRAY';
export const RESET = 'RESET';
export const INCREASE_STEP_COUNT = 'INCREASE_STEP_COUNT';
export const UPDATE_FLIPPED_CARD = 'UPDATE_FLIPPED_CARD';
export const RESET_FLIPPED_CARD = 'RESET_FLIPPED_CARD';
export const SEND_REQUEST_FLIP = 'SEND_REQUEST_FLIP';
export const FLIP_SUCCESS = 'FLIP_SUCCESS';
export const OPEN_CARD = 'OPEN_CARD';

