export const INIT_PAIR_ARRAY = 'INIT_PAIR_ARRAY';
export const RESET = 'RESET';
export const INCREASE_STEP_COUNT = 'INCREASE_STEP_COUNT';
export const OPEN_CARD = 'OPEN_CARD';
export const UPDATE_VISITED_ARRAY = 'UPDATE_VISITED_ARRAY';
